// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkqkwWtmvsvWT0-Ax3mH0T7KDGuATQm4g',
    appId: '1:787785725958:web:27b60d2ae04b895b6d2b87',
    messagingSenderId: '787785725958',
    projectId: 'ssss-f7f32',
    authDomain: 'ssss-f7f32.firebaseapp.com',
    storageBucket: 'ssss-f7f32.firebasestorage.app',
    measurementId: 'G-WF60S11H0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQMnv4cUz8A_oNhqmSYYdSUdZVIsC4EE',
    appId: '1:787785725958:android:fe8057b2c168fbc16d2b87',
    messagingSenderId: '787785725958',
    projectId: 'ssss-f7f32',
    storageBucket: 'ssss-f7f32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ5HjlZSbdtvufxBnAm-s4VH-H6m-oGMA',
    appId: '1:787785725958:ios:7a52cce8191a82b56d2b87',
    messagingSenderId: '787785725958',
    projectId: 'ssss-f7f32',
    storageBucket: 'ssss-f7f32.firebasestorage.app',
    iosBundleId: 'com.example.s',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ5HjlZSbdtvufxBnAm-s4VH-H6m-oGMA',
    appId: '1:787785725958:ios:7a52cce8191a82b56d2b87',
    messagingSenderId: '787785725958',
    projectId: 'ssss-f7f32',
    storageBucket: 'ssss-f7f32.firebasestorage.app',
    iosBundleId: 'com.example.s',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkqkwWtmvsvWT0-Ax3mH0T7KDGuATQm4g',
    appId: '1:787785725958:web:1a48cf6687883d806d2b87',
    messagingSenderId: '787785725958',
    projectId: 'ssss-f7f32',
    authDomain: 'ssss-f7f32.firebaseapp.com',
    storageBucket: 'ssss-f7f32.firebasestorage.app',
    measurementId: 'G-79H71FML75',
  );
}
